services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8090:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DB_NAME}
    env_file:
      - .secret.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://wordpress"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .secret.env
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .secret.env

networks:
  default:
    name: iot-internal-network
    external: true
    driver: bridge
